### ISSUE TITLE
How to install permanently 

### ISSUE THREAD

**Issue by shadowe1ite** [xnl-h4ck3r/XnlReveal#4]
In Firefox, the extension keeps automatically removing itself when close Firefox.

**Comment by xnl-h4ck3r** [comment]
Hi @shadowe1ite. Apologies for the very late reply. As mentioned on the [README](https://github.com/xnl-h4ck3r/XnlReveal?tab=readme-ov-file#firefox) you have to load the Fiefox extension every time. Unfortunately there is nothing I can do about this because I can't submit the extension to the Mozilla Add-ons store because it does  not use Manifest v3. They will only accept it if it does, but due to security improvments in v3, extensions like XNL Reveal will not work properly because with the increased security.
Thanks
